version: '2'

services:
  #  javaapp:
  #    build: ./java
  #    ports:
  #      - '50001:50001'

  pyapp:
    build: ./python
    ports:
      - '50002:8080'

  nodeapp:
    build: ./node
    ports:
      - '50003:8080'

  lb:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8090:80'

# MONITORING STACK
  elasticsearch:
    build: monitoring/elasticsearch/
    volumes:
      - ./monitoring/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: monitoring/logstash/
    volumes:
      - ./monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./monitoring/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: monitoring/kibana/
    volumes:
      - ./monitoring/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

